### ISSUE TITLE
Attach dont happen first time

### ISSUE THREAD

**Issue by devmondo** [whut/AttachTo#3]
Hi, 
awesome extension, saved my time, thank you very much for it.

i have weird thing going on, when i click attach to iis nothing happen, to fix this i go to chrome refresh the website page, then click attach to iis again and it works, what could be the cause of this ?

**Comment by wforney** [comment]
The worker process (w3wp) doesn't exist until you hit the site. Hitting the site spins up the worker which you can then attach to.

**Comment by devmondo** [comment]
thanks a lot that explains it well :)
